### ISSUE TITLE
V11 support

### ISSUE THREAD

**Issue by diwako** [Asinphi/Are-You-Focused#2]
Hey,
wanted to ask if there are any plans for V11 support? I tested the module on V11 for a bit, it mostly works. some quirks with detection if yourself are focused or not.

**Comment by Asinphi** [comment]
Yes, planning on updating to v11 this week. From my testing on v11, I don't notice any issues and it should just be simply declaring compatibility.
What quirks did you notice? It's intended that the module only shows the Gamemaster which players are focused and that it doesn't show whether the Gamemaster user itself is focused.

**Comment by diwako** [comment]
I do not have a repro, yet. I noticed that in rare cases the Gamemaster itself has been struck through, even if you are in that user slot active, has the application active and in focus.

At the moment I am running some Linux NodeJS v11 instance to test out a few things. Other than that it works as expected.

**Comment by r-valyar** [comment]
@Asinphi I hope everything is OK, do you still plan to update the module?

**Comment by Asinphi** [comment]
The module should work fine on v11. I haven't seen the issue of the Gamemaster's name being struck through, but I can declare v11 compatibility.
